minimatrix:
    matrix: {x: 0, y: 0, width: 128, height: 64}
    # pattern: {job: BouncingDot}
    # pattern: {job: GraphicsTest}
    pattern: {job: Life}
    # protocol: {type: Lmcp, target: minimatrix, port: 1337}
    matrixsim: {pixelsize: 10}
# megamatrix:
#     matrix: {x: 0, y: 0, width: 64, height: 32}
#     pattern: {job: BouncingDot}
#     matrixsim: {pixelsize: 10}
    # protocol: {type: Lmcp, target: megamatrix, port: 1337}
